# Generated by Django 5.1.5 on 2025-02-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cell_phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('membership_type', models.CharField(max_length=50)),
                ('membership_start_date', models.DateField()),
                ('membership_end_date', models.DateField()),
                ('membership_status', models.CharField(choices=[('Activo', 'Activo'), ('Expirado', 'Expirado'), ('Suspendido', 'Suspendido'), ('Cancelado', 'Cancelado')], default='Activo', max_length=20)),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otros', 'Otros'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('membership_notes', models.TextField(blank=True, null=True)),
                ('member_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cell_phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otros', 'Otros'), ('Prefiero no decir', 'Prefiero no decir')], max_length=20)),
                ('specialization', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('certifications', models.TextField(blank=True)),
                ('availability', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
