# Generated by Django 5.1.5 on 2025-02-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Diario', 'Diario'), ('Asistencias', 'Asistencias')], default='Diario', max_length=50),
        ),
    ]
